jakartaee/websocket

- api/client/src/main/java/javax/websocket/ClientEndpointConfig.java
- api/server/src/main/java/javax/websocket/server/ServerEndpointConfig.java
Fix #179 by removing wrapping in call to Default[Client|Server]EndpointConfig constructor
> Fix #179: Avoid double wrapping with Collections.unmodifiableList()

- api/client/src/main/java/javax/websocket/DeploymentException.java
I used a generated ID to retain compatibility with the already released class.
> Fix #233 - Serializable classes should have a serialVersionUID

- api/client/src/main/java/javax/websocket/ContainerProvider.java
> Clean up Javadoc

- api/client/pom.xml
- api/pom.xml
- api/server/pom.xml
https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates
Update spec plugin to 1.5 which is now able to validate jakarta
Maven co-ordinates
> Update groupId as per

- api/client/src/main/java/javax/websocket/ClientEndpoint.java
- api/client/src/main/java/javax/websocket/Endpoint.java
- api/client/src/main/java/javax/websocket/OnClose.java
- api/client/src/main/java/javax/websocket/OnError.java
- api/client/src/main/java/javax/websocket/OnMessage.java
- api/client/src/main/java/javax/websocket/OnOpen.java
- api/client/src/main/java/javax/websocket/WebSocketContainer.java
The EE4J_8 release branch version
The server API depends on the client API. Therefore the client API
Javadoc may not reference (via {@link ...}) the server API Javadoc as
that creates a circular reference. Therefore, replace all {@link ...}
references to the server API in the client API with {@code ...}
> Fix client Javadoc errors currently blocking the release

- api/client/pom.xml
- api/pom.xml
- api/server/pom.xml
+ Refactoring spec-version and bundle plugins to parent pom.
+ Ensuring client symbolic-name is unique to existing
server symbolic-name, and that there's no dependency
declared between them (in an OSGi sense)
> Ensuring client-api is a Bundle too.

- api/client/pom.xml
- api/server/pom.xml
This PR makes the `LICENSE.md` and `NOTICE.md` files show up in the `META-INF` directory of the two artifacts we produce.
> Ensuring that LICENSE/NOTICE shows up in META-INF

- api/client/src/main/java/jakarta/websocket/WebSocketContainer.java
**Issue #206**
This was half fixed in PR #256 but was later reverted in a formatting clean up (3b3146d1a0e7017231625b83bf30d22b7c4272e7).
> Issue #206 - Fix incorrect javadoc for WebSocketContainer connectToServer.

- spec/src/main/asciidoc/WebSocket.adoc
- spec/src/main/asciidoc/websocket-spec.adoc
This is a work in progress. I still have some changes to make and I am expecting feedback on the changes I have already made. I'm providing this more so folks can provide feedback rather than expecting it to get merged (at this point anyway).
> Spec updates

- api/pom.xml
- spec/src/main/asciidoc/WebSocket.adoc
Having updated the CI system to build with all available JDK-8, JDK-11 and JDK-latest we are getting failures on the JDK-latest builds.
This PR fixes those issues (and also includes a couple a typo fixes for the spec doc)
The main concern with this PR is that updates the source and target version from 1.6 to 8. While the code will compile with Java 6 I thnk it is time to update these so we/users can build with newer versions of Java.
> Updates to build with latest java

- api/pom.xml
- spec/pom.xml
Despite the builds running locally, CI continued to fail. I'm not sure why. Versions used were the same as far as I could tell.
Updating the Maven enforcer plug-in fixed the CI builds with the various latest JDKs. I ran the CI against the same branch this PR is generated from to make sure.
> Fix CI failures with latest JDKs

- api/client/src/main/java/jakarta/websocket/RemoteEndpoint.java
> Fix #232. Clarify behaviour of getSendWriter() and getSendStream()

- api/client/src/main/java/jakarta/websocket/RemoteEndpoint.java
> Fix #223. Relax requirement for call-backs to be on a different thread

- api/client/src/main/java/jakarta/websocket/HandshakeResponse.java
- api/server/src/main/java/jakarta/websocket/server/HandshakeRequest.java
> Fix #231 - Clarify how HTTP headers are exposed through the API

- spec/src/main/asciidoc/WebSocket.adoc
Note that this does not address encoder search order which will have to wait until Jakarta EE 10.
> Fix #220 - clarify Encoders match types and sub-types

- api/client/src/main/java/jakarta/websocket/RemoteEndpoint.java
This is only a small part of what is required but I think this is all we can reasonably do for Jakarta EE 9.
> Add clarity to Javadoc around use of Encoders

- api/client/src/main/java/jakarta/websocket/Decoder.java
- api/client/src/main/java/jakarta/websocket/RemoteEndpoint.java
This reflects the results of an EG discussion from 2013:
https://download.oracle.com/javaee-archive/websocket-spec.java.net/jsr356-experts/2013/03/0492.html
> Fix #209 - clarify how ByteBuffers are used

- api/client/src/main/java/jakarta/websocket/Session.java
> Fix #203 - clarify return value of getRequestParameterMap()

- spec/src/main/asciidoc/WebSocket.adoc
Minor re-wording to clarify intent (which is consistent with the TCK)
> Fix #201 - clarify @On[Open|Close|Error] may only appear on one method

- spec/src/main/asciidoc/WebSocket.adoc
Looking at the Tomcat unit tests I see there is an explicit test that
/a/{var} does not match /a/b/ as a result of EG discussion.
> Fix #195 - explicitly state /a/{var} does not match /a/b/

- spec/src/main/asciidoc/WebSocket.adoc
I don't believe this goes any further than what is already either implied in the specification text or required by common sense but definitely worth a double check.
> Fix #194 - be more specific about permitted endpoint paths and mapping

- api/client/src/main/java/jakarta/websocket/ContainerProvider.java
No change in behaviour. Just being more explicit so callers know what to
expect.
> Fix #254 - document behaviour on error in the Javadoc

- api/server/pom.xml
- spec/pom.xml
Override parent rather than add to
Fixes an issue where the source JAR build by CI misses some classes. Not observed on local build - possibly due to different maven command to CI deploy job.
> Fix content of source JAR

- api/server/pom.xml
This POM has a custom source JAR config so disabling the one from the
EE4J parent prevents the possibility of the wrong source JAR
over-writing the correct one (plug-in execution order can vary).
> Disable source JAR config from EE4J parent

- api/client/pom.xml
- api/server/pom.xml
Task-Url: https://github.com/eclipse-ee4j/websocket-api/issues/357
Signed-off-by: Werner Keil <werner.keil@gmx.net>
> 357: Remove the automatic module names

- api/client/src/main/java/jakarta/websocket/Session.java
- spec/src/main/asciidoc/WebSocket.adoc
To quote gregw "Once you start a websocket message, you continue to use
the same MessageHandler for the entire message."
> Fix #190 and #192. Clarify messages and MessageHandler add/remove

- api/client/pom.xml
- api/client/src/main/java/module-info.java
- api/pom.xml
- api/server/pom.xml
- api/server/src/main/java/module-info.java
- spec/src/main/asciidoc/WebSocket.adoc
The server jar no longer contains a copy of the client classes. The copy has been replaced by a dependency.
> Refactor the packaging for JPMS and add module-info

- api/pom.xml
- api/server/pom.xml
Better to specify server JAR specific properties in the server POM
rather than in the parent POM.
> Follow-up to #393. Move server JAR properties to server POM

- api/client/pom.xml
- api/client/src/main/javadoc/doc-files/EFSL.html
- api/pom.xml
- api/server/pom.xml
- api/server/src/main/javadoc/doc-files/EFSL.html
- pom.xml
- spec/pom.xml
- spec/src/main/asciidoc/WebSocket.adoc
- spec/src/main/asciidoc/license-efsl.adoc
It isn't clear at this point if the next release will be 2.2 or 3.0 so start with 2.2 and we can always change it to 3.0 later if required.
> Update version to 2.2 and year to 2022 for next development cycle.

- README.md
The word 'defines' was typed twice in a row within the readme file.
> fix a minor typo in the readme

- api/client/src/main/java/jakarta/websocket/OnMessage.java
- spec/src/main/asciidoc/WebSocket.adoc
Given that `Integer.MAX_VALUE` is the practical limit on message length I opted to deprecate the existing annotation attribute and replace it with once that used `int`.
I did wonder about adding a note about the practical limit on message size.
> Fix #274 - Correct message buffer configuration inconsistency

- tck/spec-tests/src/main/java/com/sun/ts/tests/websocket/ee/jakarta/websocket/server/serverendpointconfig/configurator/WSCModifyHandshakeServer.java
There is no text in the specification document nor the Javadoc that would require the ServerEndpoint presented to the Configurator to be the same as the one presented to @OnOpen
> Fix #478 - TCK should only test for type

- api/client/src/main/java/jakarta/websocket/ClientEndpointConfig.java
- spec/src/main/asciidoc/WebSocket.adoc
- tck/spec-tests/src/main/java/com/sun/ts/tests/websocket/ee/jakarta/websocket/handshakeresponse/WSCClientIT.java
Fix #417 
The PR updates the Javadoc for `.Configurator.afterResponse(HandshakeResponse) ` adds a new TCK test and updates the specification change log.
There are also some clean-ups to the files touched by this PR in separate commits.
> Fix #417 - Also call ClientEndPoint.Configurator.afterResponse(HandshakeResponse) on failed handshakes
