.travis.yml

I did not see any tests in this project, but we'll at least know that build still works.

Added Travis CI.

---

api/client/src/main/java/javax/websocket/Decoder.java

Fix issue 208: Correct Javadoc copy/paste error

---

api/client/src/main/java/javax/websocket/ContainerProvider.java

Refactor to use currently dead code as originally intended

---

.gitignore

Ignore IDE files

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml

Per recommendations at https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates

Using correct maven artifactIds 

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml

Looking at other projects (jaxrs-api and jsonp) there are a few pom entries that need to be updated for later OSSRH requirements.

Websocket pom updates for OSSRH

---

api/client/pom.xml
api/server/pom.xml

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

Version fix for release

---

api/pom.xml

Fix duplicate plug-in definition

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml

This is the merge of the 3 recent PRs (#283 #284 #285)

EE4J_8 Merge

---

CONTRIBUTING.md
NOTICE.md
api/client/pom.xml
api/client/src/main/java/javax/websocket/Session.java
api/client/src/main/java/javax/websocket/package-info.java
api/pom.xml
api/server/pom.xml
api/server/src/main/java/javax/websocket/server/package-info.java
pom.xml
websocket-1.1-changes.txt

Issue #295 - update master text references to conform to Jakarta standards

---

CONTRIBUTING.md
NOTICE.md
api/client/pom.xml
api/client/src/main/java/javax/websocket/Session.java
api/client/src/main/java/javax/websocket/package-info.java
api/pom.xml
api/server/pom.xml
api/server/src/main/java/javax/websocket/server/package-info.java
pom.xml
websocket-1.1-changes.txt

Issue #295 - update EE4J_8 text references to conform to Jakarta standards

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml
pom.xml
spec/pom.xml

Issue #295 - Bumping up master version to 1.1.2 per Jakarta Guide

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml
pom.xml
spec/pom.xml

Issue #295 - Bumping up EE4J_8 version to 1.1.2 per Jakarta Guide

---

api/pom.xml
spec/src/main/asciidoc/license-efsl.adoc

Issue #306 - Add the Eclipse copyright to spec and javadocs

---

spec/src/main/asciidoc/WebSocket.adoc
spec/src/main/asciidoc/websocket-spec.adoc

Signed-off-by: Ivar Grimstad <ivar.grimstad@eclipse-foundation.org>

Add initial contribution of spec document

---

spec/pom.xml

As seen in review of PR #312 this updates the spec/pom.xml JVM enforcer rule.

Update JVM enforcer rule to be consistent with other Jakarta projects

---

.gitignore

Update .gitignore to ignore spec target dir

---

.travis.yml
api/pom.xml

Should fix the cause of the Travis failure with jdk9

Fix Travis CI build failures

---

api/pom.xml
spec/pom.xml
spec/src/main/asciidoc/WebSocket.adoc
spec/src/main/asciidoc/license-efsl.adoc
spec/src/main/asciidoc/websocket-spec.adoc

Just some minor fixes / clean-up

Spec cleanup

---

spec/src/main/asciidoc/WebSocket.adoc
spec/src/main/asciidoc/license-efsl.adoc
spec/src/main/asciidoc/websocket-spec.adoc

Proof read the converted spec.
Remove the (per spec-leads list) unnecessary historic changes appendices.
Improved section cross-references.
Fixed a few typos.

Proof reading of spec doc

---

spec/src/main/asciidoc/WebSocket.adoc
spec/src/main/asciidoc/license-efsl.adoc

Specification polishing after comparing the current draft with the 1.1 specification document.

Spec polish

---

CONTRIBUTING.md

Fixes #330 
Add section on Eclipse Development Process
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

#330 Eclipse Development Process

---

api/client/pom.xml
api/pom.xml

Add Automatic-Module-Name

---

api/client/src/main/java/jakarta/websocket/Endpoint.java

The other aspects of this issue are being handled / have been handled elsewhere.

Fix #191 - clarify what is permitted in OnOpen

---

api/client/src/main/javadoc/doc-files/EFSL.html
api/pom.xml
api/server/src/main/javadoc/doc-files/EFSL.html
spec/pom.xml
spec/src/main/asciidoc/license-efsl.adoc

I also compared this with the equivalent EL files and included a couple of changes to keep them aligned.

Fix #341 - update EFSP references per guidance from platform-dev

---

pom.xml

Fix license / copyright header

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml
pom.xml
spec/pom.xml

I've reviewed the WebSocket POMs against those in EL and JSP and attempted to align them as best I can. The idea is that keeping them align simplifies maintenance as a fix/enhancement in one, can easily be transferred to the others. Overall, this removes some unnecessary config, corrects a few errors and updates a bunch of plugins.

Pom alignment

---

api/pom.xml

Align IDs so correct packages appear in releases

---

spec/src/main/asciidoc/WebSocket.adoc

Update references to use Jakarta specifications

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml
pom.xml
spec/pom.xml

Update branch 2.0.0 for restage

---

api/client/src/main/java/jakarta/websocket/package-info.java

Fixing typo in javadoc

---

api/server/src/main/java/jakarta/websocket/server/ServerEndpointConfig.java

Make ServerEndpointConfig.Configurator.getContainerDefaultConfigurator()
public.

Fix #207 Expose the platform default configurator directly

---

api/client/src/main/java/jakarta/websocket/ClientEndpointConfig.java
api/client/src/main/java/jakarta/websocket/DefaultClientEndpointConfig.java
spec/src/main/asciidoc/WebSocket.adoc

This is a PR for v3 of the solution for this issue. I believe it addresses the concerns raised with v1 (#372) and v2 (#378)

Fix #210 - Add an API for client-side TLS configuration

---

api/client/pom.xml

Signed-off-by: jansupol <jan.supol@oracle.com>

Make client jar OSGi symbolic name header unique

---

api/pom.xml

Use same approach as EL and JSP

OSGi bundle version should be consistent with project version

---

api/client/src/main/java/jakarta/websocket/ContainerProvider.java

Fixes https://github.com/jakartaee/websocket/issues/403

Fix #403 - Adding doPrivileged block to work properly in environments with installed security manager

---

spec/src/main/asciidoc/WebSocket.adoc

I plan to leave this PR open for a week or two for comments and then, depending on the comments, amend or merge the PR.

Fix #176 - clarify ping message responsibilities

---

spec/src/main/asciidoc/WebSocket.adoc

I'm not expecting this to be controversial, so I plan to merge immediately.

Add paragraph briefly describing new HttpSession.getAccessor() method

---

api/client/src/main/javadoc/doc-files/EFSL.html
api/server/src/main/javadoc/doc-files/EFSL.html

Updates the EFSL for the Javadoc

Update EFSL from 1.0 to 1.1

---

api/client/pom.xml
api/pom.xml
api/server/pom.xml
pom.xml
spec/pom.xml
spec/src/main/asciidoc/WebSocket.adoc

No decision has been made on 2.3 vs 3.0 at the moment so work on the assumption the next release will be 2.3.

Bump version from 2.2. to 2.3

---

tck/spec-tests/pom.xml

Fix issue 489

---

api/pom.xml

For publishing to Maven Central

Update parent POM to 2.0.0-SNAPSHOT
